name: Jekyll Version of Pattern Primer by adactio
markdown: redcarpet
pygments: false
# change baseurl to:
# '': for root level domains ie: mycustomdomain.com
projecturl: http://cruweb.github.io/patterns/ #'/projectname': for subdomains ie: user.github.io/projectname
baseurl: '/'
permalink: patterns/:title.html
exclude: ['s3_website.yml']
safe: false